services:
  db:
    container_name: postgresTemplate
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      custom_network:
        ipv4_address: 10.100.0.2  # Static IP address for the db service
    volumes:
      - postgres_data:/data/postgres
    command: -p ${POSTGRES_PORT}

  pgadmin:
    container_name: pgadmin4Template
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "80:80"
    networks:
      custom_network:
        ipv4_address: 10.100.0.3  # Static IP address for the db service
    volumes:
       - pgadmin:/var/lib/pgadmin
  redis:
    image: docker.io/bitnami/redis:7.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      custom_network:
        ipv4_address: 10.100.0.4

volumes:
  redis_data:
    driver: local
  pgadmin:
  postgres_data:
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16  # Define subnet to include your chosen IP
